version: '3.9'
services:
  emojiutilities:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: sethcohendev/emojiutilities:latest
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: