version: '3.8'
services:
  emojiutilities:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    env_file:
      - .env
    image: sethcohendev/emojiutilities:latest
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: